### ISSUE TITLE
Automate regular updates of the bootstrap bundle 

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/on-prem-builder#127]
Core plans are a constantly moving target, which means the bootstrap bundle is often out of date. We should automate regular updates of the bundle (monthly?) to minimize the delta between the bundle and the stable channel on the Public Builder service.

**Comment by qubitrenegade** [comment]
What is the current process?  I have a few spare cycles week after next and would like to take a crack at this.

**Comment by bdangit** [comment]
@qubitrenegade they actually have a command built in to on-prem-archive script that will generate an archive and upload it to AWS buckets.

**Comment by jsirex** [comment]
I'm still in "developing-refactoring", but decided to push a scratch commit with `hab-depot-sync`.
It, probably, buggy, but I was able to incremental sync only latest packages. Syncing doesn't require disk space.

Unfortunately you have to:
1. have ruby
2. clone https://github.com/habitat-plans/hab-sdk.git
3. `rake build && rake install`

Try `hab-depot-sync --help`

**Comment by jsirex** [comment]
Work still in progress. Now I have habitat:
```bash
sudo hab pkg install -b ya/hab-sdk -c unstable
hab-depot-sync --dest-depot https://bldr.on-prem.domain.local --dest-auth-token $auth_token --origin core --latest-version
```

**Comment by bdangit** [comment]
@jsirex I tried to run your app but i get this:

```
SSL_CERT_FILE=/my/pem hab-depot-sync --dest-depot https://bldr.myonprem --dest-auth-token $HAB_AUTH_TOKEN --origin core --latest-release
   Warn: unexpected response for https://bldr.myonprem/v1/depot/origins/core/keys. Net::HTTPBadGateway - <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.15.6</center>
</body>
</html>
Traceback (most recent call last):
        7: from /usr/bin/hab-depot-sync:13:in `<main>'
        6: from /usr/bin/hab-depot-sync:13:in `load'
        5: from /hab/pkgs/ya/hab-sdk/0.1.0/20190304151756/rubygems/gems/hab-sdk-0.1.0/exe/hab-depot-sync:5:in `<top (required)>'
        4: from /hab/pkgs/ya/hab-sdk/0.1.0/20190304151756/rubygems/gems/hab-sdk-0.1.0/lib/hab/depot/sync.rb:68:in `run'
        3: from /hab/pkgs/ya/hab-sdk/0.1.0/20190304151756/rubygems/gems/hab-sdk-0.1.0/lib/hab/depot/sync.rb:164:in `list_origin_keys'
        2: from /hab/pkgs/core/ruby/2.5.3/20190131191657/lib/ruby/2.5.0/json/common.rb:156:in `parse'
        1: from /hab/pkgs/core/ruby/2.5.3/20190131191657/lib/ruby/2.5.0/json/common.rb:156:in `new'
/hab/pkgs/core/ruby/2.5.3/20190131191657/lib/ruby/2.5.0/json/common.rb:156:in `initialize': no implicit conversion of nil into String
```

**Comment by bdangit** [comment]
@jsirex sorry false alarm! our bldr had some production issues which got resolved.  Script appears to be working.  I'll share results after it finishes.

**Comment by jsirex** [comment]
@bdangit have you succeed?

**Comment by bdangit** [comment]
@jsirex I have been successful.  thanks for checking in
